### ISSUE TITLE
Github oauth not working

### ISSUE THREAD

**Issue by itsthejoker** [FriendsOfFlarum/oauth#78]
## Bug Report

**Current Behavior**
Unable to sign up using the GitHub Oauth handler. 

**Steps to Reproduce**
1. Enable GitHub oauth flow with new app
2. log out
3. click 'sign in'
4. go through oauth flow
5. land back at app at the 'choose username' screen, click 'sign up'
6. see error

**Expected Behavior**
Signup will complete.

**Screenshots**

<img width="409" alt="image" src="https://github.com/FriendsOfFlarum/oauth/assets/5179553/f0a6f6d5-8d4a-4d0c-925b-89e0968936e7">

**Environment**
- Flarum version: 1.8.5
- Extension version: 1.6.10 
- Website URL: https://forum.filamentcolors.xyz
- Webserver: nginx
- Hosting environment: vps
- PHP version: 8.3
- Browser: Firefox 127.0.2

```
Flarum core: 1.8.5
PHP version: 8.3.6
MySQL version: 10.11.8-MariaDB-0ubuntu0.24.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+------------------------+---------+--------+
| Flarum Extensions      |         |        |
+------------------------+---------+--------+
| ID                     | Version | Commit |
+------------------------+---------+--------+
| flarum-tags            | v1.8.0  |        |
| flarum-suspend         | v1.8.1  |        |
| fof-pages              | 1.0.8   |        |
| fof-webhooks           | 1.2.3   |        |
| fof-user-bio           | 1.4.0   |        |
| fof-sitemap            | 2.2.1   |        |
| fof-profile-image-crop | 1.1.6   |        |
| fof-oauth              | 1.6.10  |        |
| fof-nightmode          | 1.5.3   |        |
| fof-links              | 1.2.3   |        |
| fof-github-autolink    | 1.1.4   |        |
| fof-best-answer        | 1.4.4   |        |
| flarum-subscriptions   | v1.8.0  |        |
| flarum-sticky          | v1.8.0  |        |
| flarum-statistics      | v1.8.0  |        |
| flarum-mentions        | v1.8.3  |        |
| flarum-markdown        | v1.8.0  |        |
| flarum-lock            | v1.8.0  |        |
| flarum-likes           | v1.8.0  |        |
| flarum-lang-english    | v1.8.0  |        |
| flarum-flags           | v1.8.0  |        |
| flarum-emoji           | v1.8.0  |        |
| flarum-bbcode          | v1.8.0  |        |
| datlechin-pronouns     | v0.1.0  |        |
| danirod-plausible      | v1.1.0  |        |
| blomstra-fontawesome   | 0.1.5   |        |
+------------------------+---------+--------+
Base URL: https://forum.filamentcolors.xyz
Installation path: /var/www/html
Queue driver: sync
Session driver: file
Scheduler status: Never run
Mail driver: smtp
Debug mode: off
```

**Possible solution(s)**

**Additional Context**
```
[2024-07-02 03:37:37] flarum.ERROR: Intervention\Image\Exception\NotReadableException: Unable to init from given url (https://avatars.githubusercontent.com/u/5179553?v=4). in /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:85
Stack trace:
#0 /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(335): Intervention\Image\AbstractDecoder->initFromUrl()
#1 /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(66): Intervention\Image\AbstractDecoder->init()
#2 /var/www/html/vendor/intervention/image/src/Intervention/Image/ImageManager.php(54): Intervention\Image\AbstractDriver->init()
#3 /var/www/html/vendor/flarum/core/src/User/Command/RegisterUserHandler.php(164): Intervention\Image\ImageManager->make()
#4 /var/www/html/vendor/flarum/core/src/User/Command/RegisterUserHandler.php(129): Flarum\User\Command\RegisterUserHandler->uploadAvatarFromUrl()
#5 /var/www/html/vendor/flarum/core/src/User/Command/RegisterUserHandler.php(101): Flarum\User\Command\RegisterUserHandler->applyToken()
#6 /var/www/html/vendor/illuminate/bus/Dispatcher.php(122): Flarum\User\Command\RegisterUserHandler->handle()
#7 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#8 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /var/www/html/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#10 /var/www/html/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#11 /var/www/html/vendor/flarum/core/src/Api/Controller/CreateUserController.php(45): Illuminate\Bus\Dispatcher->dispatch()
#12 /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(116): Flarum\Api\Controller\CreateUserController->data()
#13 /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\Api\Controller\AbstractSerializeController->handle()
#14 /var/www/html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractCreateController->handle()
#15 /var/www/html/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#16 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#17 /var/www/html/vendor/fof/oauth/src/Middleware/BindRequest.php(33): Laminas\Stratigility\Next->handle()
#18 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\BindRequest->process()
#19 /var/www/html/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#20 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\ThrottleApi->process()
#21 /var/www/html/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#22 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#23 /var/www/html/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#24 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#25 /var/www/html/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#26 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#27 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#28 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#29 /var/www/html/vendor/flarum/core/src/Api/Client.php(141): Laminas\Stratigility\MiddlewarePipe->handle()
#30 /var/www/html/vendor/flarum/core/src/Api/Client.php(96): Flarum\Api\Client->send()
#31 /var/www/html/vendor/flarum/core/src/Forum/Controller/RegisterController.php(56): Flarum\Api\Client->post()
#32 /var/www/html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Forum\Controller\RegisterController->handle()
#33 /var/www/html/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#34 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#35 /var/www/html/vendor/fof/oauth/src/Middleware/BindRequest.php(33): Laminas\Stratigility\Next->handle()
#36 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\BindRequest->process()
#37 /var/www/html/vendor/fof/oauth/src/Middleware/ErrorHandler.php(58): Laminas\Stratigility\Next->handle()
#38 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\ErrorHandler->process()
#39 /var/www/html/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#40 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#41 /var/www/html/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#42 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#43 /var/www/html/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#44 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#45 /var/www/html/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#46 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#47 /var/www/html/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#48 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process()
#49 /var/www/html/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#50 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#51 /var/www/html/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#52 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#53 /var/www/html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#54 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process()
#55 /var/www/html/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#56 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process()
#57 /var/www/html/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#58 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process()
#59 /var/www/html/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#60 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CollectGarbage->process()
#61 /var/www/html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#62 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process()
#63 /var/www/html/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#64 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#65 /var/www/html/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#66 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process()
#67 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#68 /var/www/html/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#69 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process()
#70 /var/www/html/vendor/middlewares/base-path-router/src/BasePathRouter.php(99): Laminas\Stratigility\Next->handle()
#71 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process()
#72 /var/www/html/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#73 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process()
#74 /var/www/html/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#75 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process()
#76 /var/www/html/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#77 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process()
#78 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#79 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#80 /var/www/html/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#81 /var/www/html/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#82 /var/www/html/public/index.php(26): Flarum\Http\Server->listen()
#83 {main}
```

**Comment by dsevillamartin** [comment]
Do you have `allow_url_fopen` enabled in PHP settings? A quick search seems to indicate that it being disabled can cause problems. I tested it locally and signup through GitHub with a profile picture worked fine for me.

**Comment by itsthejoker** [comment]
@dsevillamartin I do — `phpinfo` gives `allow_url_fopen => On => On`. I've never worked with PHP before, so I'm not sure what's a good question or not 😅

**Comment by dsevillamartin** [comment]
Is there maybe another exception next to that one? Cause that error isn't very detailed... I'd hope there's a more detailed exception thrown alongside it lol

**Comment by itsthejoker** [comment]
I will re-trigger it and check the logs again 👍

**Comment by itsthejoker** [comment]
Unfortunately it appears to be the same. This is the only entry in the log file for today.

<details>
<summary>click to expand</summary>

```
[2024-07-07 15:56:02] flarum.ERROR: Intervention\Image\Exception\NotReadableException: Unable to init from given url (https://avatars.githubusercontent.com/u/5179553?v=4). in /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php:85
Stack trace:
#0 /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(335): Intervention\Image\AbstractDecoder->initFromUrl()
#1 /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(66): Intervention\Image\AbstractDecoder->init()
#2 /var/www/html/vendor/intervention/image/src/Intervention/Image/ImageManager.php(54): Intervention\Image\AbstractDriver->init()
#3 /var/www/html/vendor/flarum/core/src/User/Command/RegisterUserHandler.php(164): Intervention\Image\ImageManager->make()
#4 /var/www/html/vendor/flarum/core/src/User/Command/RegisterUserHandler.php(129): Flarum\User\Command\RegisterUserHandler->uploadAvatarFromUrl()
#5 /var/www/html/vendor/flarum/core/src/User/Command/RegisterUserHandler.php(101): Flarum\User\Command\RegisterUserHandler->applyToken()
#6 /var/www/html/vendor/illuminate/bus/Dispatcher.php(122): Flarum\User\Command\RegisterUserHandler->handle()
#7 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#8 /var/www/html/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#9 /var/www/html/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#10 /var/www/html/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow()
#11 /var/www/html/vendor/flarum/core/src/Api/Controller/CreateUserController.php(45): Illuminate\Bus\Dispatcher->dispatch()
#12 /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(116): Flarum\Api\Controller\CreateUserController->data()
#13 /var/www/html/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\Api\Controller\AbstractSerializeController->handle()
#14 /var/www/html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractCreateController->handle()
#15 /var/www/html/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#16 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#17 /var/www/html/vendor/fof/oauth/src/Middleware/BindRequest.php(33): Laminas\Stratigility\Next->handle()
#18 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\BindRequest->process()
#19 /var/www/html/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#20 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\ThrottleApi->process()
#21 /var/www/html/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#22 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#23 /var/www/html/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#24 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#25 /var/www/html/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#26 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#27 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#28 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#29 /var/www/html/vendor/flarum/core/src/Api/Client.php(141): Laminas\Stratigility\MiddlewarePipe->handle()
#30 /var/www/html/vendor/flarum/core/src/Api/Client.php(96): Flarum\Api\Client->send()
#31 /var/www/html/vendor/flarum/core/src/Forum/Controller/RegisterController.php(56): Flarum\Api\Client->post()
#32 /var/www/html/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Forum\Controller\RegisterController->handle()
#33 /var/www/html/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#34 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#35 /var/www/html/vendor/fof/oauth/src/Middleware/BindRequest.php(33): Laminas\Stratigility\Next->handle()
#36 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\BindRequest->process()
#37 /var/www/html/vendor/fof/oauth/src/Middleware/ErrorHandler.php(58): Laminas\Stratigility\Next->handle()
#38 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): FoF\OAuth\Middleware\ErrorHandler->process()
#39 /var/www/html/vendor/flarum/core/src/Http/Middleware/ContentTypeOptionsHeader.php(21): Laminas\Stratigility\Next->handle()
#40 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ContentTypeOptionsHeader->process()
#41 /var/www/html/vendor/flarum/core/src/Http/Middleware/ReferrerPolicyHeader.php(30): Laminas\Stratigility\Next->handle()
#42 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ReferrerPolicyHeader->process()
#43 /var/www/html/vendor/flarum/core/src/Http/Middleware/FlarumPromotionHeader.php(30): Laminas\Stratigility\Next->handle()
#44 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\FlarumPromotionHeader->process()
#45 /var/www/html/vendor/flarum/core/src/Http/Middleware/ShareErrorsFromSession.php(57): Laminas\Stratigility\Next->handle()
#46 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ShareErrorsFromSession->process()
#47 /var/www/html/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle()
#48 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process()
#49 /var/www/html/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#50 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#51 /var/www/html/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#52 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#53 /var/www/html/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#54 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process()
#55 /var/www/html/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#56 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process()
#57 /var/www/html/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#58 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process()
#59 /var/www/html/vendor/flarum/core/src/Http/Middleware/CollectGarbage.php(46): Laminas\Stratigility\Next->handle()
#60 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CollectGarbage->process()
#61 /var/www/html/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#62 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process()
#63 /var/www/html/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#64 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#65 /var/www/html/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#66 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process()
#67 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#68 /var/www/html/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#69 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process()
#70 /var/www/html/vendor/middlewares/base-path-router/src/BasePathRouter.php(99): Laminas\Stratigility\Next->handle()
#71 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process()
#72 /var/www/html/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#73 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process()
#74 /var/www/html/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#75 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process()
#76 /var/www/html/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#77 /var/www/html/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process()
#78 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#79 /var/www/html/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#80 /var/www/html/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#81 /var/www/html/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#82 /var/www/html/public/index.php(26): Flarum\Http\Server->listen()
#83 {main}
```

</details>

**Comment by bashlk** [comment]
I ran into the same issue and setting allow_url_fopen to On fixed the issue. The issue also occurred when I tried to sign up using Google.

Now I need to figure out how to set it only for the flarum site on my web hosting provider (Hetzner) since from what I see, allow_url_fopen is best left disabled globally. I tried setting `php_flag allow_url_fopen On` in `.htaccess` file in the public folder but phpinfo reported that it was not being turned on  🤔

**Comment by itsthejoker** [comment]
Fascinating... I haven't touched it since I started this issue, so maybe I need to go futz with it again. Gah, this is frustrating.

**Comment by belousovjr** [comment]
I also encounter the error "Unable to init from given url"... 
If this is related to loading an avatar during registration, maybe the respected authors can add an option to the configuration interface so that the avatar can be disabled?... (I work with FreeFlarum)
